version: '3.8'

services:
  app:
    build: .
    container_name: currency-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - APY_API_KEY=${APY_API_KEY}  # Load the API key from the environment
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
